# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.cache/wt [current_project]
set_property parent.project_path C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Desktop/Audio_Input.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/B_Task.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/B_Task_Run.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/BackButton.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/Group_Task_7Seg.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Group_seven_seg_D.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Menu.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/MorseLogic.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/MorseTest.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/Morse_Oled.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/Oled_Display.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Oled_DisplayOriginal.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Oled_Number_Display_D.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/StudentA.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/StudentB.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/StudentC.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/Top_Student.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Top_Student_D.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/alternatebeam.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/animate.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/animate_venusaur.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/circle.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/clk_instance.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/clown.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/crack.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/crackinv.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/display_count_on_seg.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/display_seg_an_led.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/find_volume_level.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/group_oled.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/hell.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/impr_c.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/improvement.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/menu_UI_student_A.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/menu_UI_student_B.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/menu_UI_student_C.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/menu_UI_student_D.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/menu_UI_student_G.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/message.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/mood.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/morsecode.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/music.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/my_clk_divider.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/oled_number_display.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/paint.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/paint_app.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/paint_application.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/pixel_XY.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/rain.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/recognition.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/sad.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/shooting.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/stressmenu.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/task.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/toneMenu.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/tonePlay.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/new/toneSetter.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/venusaurcharge.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/venusaurhappy.v
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Main_menu.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Desktop/Audio_Output.vhd
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Desktop/Mouse_Control.vhd
  C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/sources_1/imports/Desktop/Ps2Interface.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/seets/OneDrive/Desktop/joohoe/MenuLogicTrial/MenuLogicTrial.srcs/constrs_1/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Main_menu -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main_menu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_menu_utilization_synth.rpt -pb Main_menu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
